---
- name: Set fact nagios_mac_install_base
  ansible.builtin.set_fact:
    nagios_mac_install_base: /usr/local

- name: Set fact nagios_mac_install_base arm64
  ansible.builtin.set_fact:
    nagios_mac_install_base: /opt/homebrew
  when: ansible_architecture == "arm64"

- name: Ensure nrpe_group exists
  ansible.builtin.group:
    name: "{{ nrpe_group }}"
    state: present

- name: Ensure nrpe_user exists
  ansible.builtin.user:
    name: "{{ nrpe_user }}"
    shell: /bin/false
    groups: "{{ nrpe_group }}"
    append: true

# test on arm cpu also
- name: Check if brew is installed
  ansible.builtin.shell: |
    export PATH=/usr/local/bin:/opt/homebrew/bin:$PATH
    command -v brew
  args:
    executable: /bin/bash
  register: does_brew_exist
  ignore_errors: true
  changed_when: false

- name: Install brew
  ansible.builtin.command: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  when: does_brew_exist.rc
  changed_when: true

- name: Set fact nrpe_plugin_dir_default
  ansible.builtin.set_fact:
    nrpe_plugin_dir: "{{ nagios_mac_install_base }}/opt/nagios-plugins/libexec/sbin"

# Just ran into this problem. A conflict with prometheus.
# Might solve it another way in the future.
- name: Fix dir permissions  # noqa no-free-form
  ansible.builtin.shell: |
    chmod g+w {{ nagios_mac_install_base }}/var/log
  args:
    executable: /bin/bash
  failed_when: false
  changed_when: false

- name: Install nagios-plugins
  community.general.homebrew:
    name: nagios-plugins
    state: present
  become: false

- name: Install nrpe
  community.general.homebrew:
    name: nrpe
    state: present
  become: false

- name: LaunchDaemon config
  ansible.builtin.template:
    src: homebrew.mxcl.nrpe.plist
    dest: /Library/LaunchDaemons/homebrew.mxcl.nrpe.plist
    owner: root
    group: wheel
    mode: "0755"
  notify: Restart nrpe osx

- name: Remove default LaunchDaemon config
  ansible.builtin.file:
    path: /Users/administrator/Library/LaunchAgents/homebrew.mxcl.nrpe.plist
    state: absent

# Install custom plugins here:
# - name: Install check_mem plugin
#  copy: src=files/check_mem dest={{ nrpe_plugin_dir }}/check_mem mode=755

- name: NRPE config file
  ansible.builtin.template:
    src: nrpe.cfg
    dest: "{{ nagios_mac_install_base }}/etc/nrpe.cfg"
    owner: administrator
    group: admin
    mode: "0644"
  notify: Restart nrpe osx

- name: Create nrpe.d dir
  ansible.builtin.file:
    path: "{{ nrpe_conf_dir }}/nrpe.d"
    state: directory
    owner: administrator
    group: admin
    mode: "0755"

- name: NRPE checks
  ansible.builtin.template:
    src: nrpe_check.cfg
    dest: "{{ nrpe_conf_dir }}/nrpe.d/{{ item.key }}.cfg"
    owner: administrator
    group: admin
    mode: "0644"
  with_dict: "{{ nrpe_checks }}"
  notify: Restart nrpe osx

- name: Ensure nrpe is started
  ansible.builtin.command: |
    launchctl load /Library/LaunchDaemons/homebrew.mxcl.nrpe.plist
  changed_when: false
